# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a98e00674e00da851db776a56ac3150d"
name = "admin-action-block"
handle = "admin-action-block-1"
application_url = "https://admin-action-block--development.gadget.app/api/shopify/install-or-render"
embedded = true

[build]
dev_store_url = "codeinspire2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_orders,write_orders,write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://admin-action-block--development.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
